name: 'Build and push Docker image'
description: 'Build and push a single Docker image to Github Container Registry, ghcr.io.'

inputs:
  token:
    description: 'GitHub Token {{ secrets.GITHUB_TOKEN }} with the privilege set to write packages.'
    required: true
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Dockerfile location'
    required: false
    default: 'Dockerfile'
  build-args:
    description: 'List of build-time variables for the Dockerfile'
    required: false
  pull-requests:
    description: 'If pull requests should be pushed to the registry or not.'
    required: false
    default: false

runs:
  using: "composite"
  steps:

    - name: Login to GitHub Container Registry
      #if: inputs.pull-request || github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.pull-requests || github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          ${{ inputs.build-args }}
